image: dmiski/verilatordocker

stages:
  - build
  - test

build:linux:
  stage: build
  tags:
    - linux

  script:
    - cd tb
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja
    - cmake --build .

  artifacts:
    expire_in: 2 hrs
    paths:
      - ./tb/build/

test:linux:
  stage: test
  tags:
    - linux
  script:
    - ./tb/build/VerilatorTest --reporter JUnit::out=report.xml --reporter console::out=-::colour-mode=ansi
    - ls ./tb/build/*
  artifacts:
    when: always
    reports:
      junit: report.xml
  dependencies:
    - build:linux

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'
